### ISSUE TITLE
Build failing due to version change

### ISSUE THREAD

**Issue by jmzo** [medikoo/timers-ext#2]
looking at this commit...
https://github.com/medikoo/timers-ext/commit/8508aa14e060bff757ad27c65f3013c03a05568b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R19

...it appears that `es5-ext` dependency was revved up to `~0.10.14` which throws this error in my build...

`npm ERR! notarget No compatible version found: es5-ext@~0.10.14
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.10.13, 0.10.12, 0.10.11, 0.10.10, 0.10.9, 0.10.8, 0.10.7, 0.10.6, 0.10.5, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.9.2, 0.9.1, 0.9.0, 0.8.2, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.1, 0.5.0, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'timers-ext'`

**Comment by jmzo** [comment]
although... maybe it is a caching issue on my side. Feel free to close

**Comment by medikoo** [comment]
@jmzo yes, it looks as caching issue, as [v0.10.14](https://www.npmjs.com/package/es5-ext) was published few hours before this version of timers-ext, and it appears your setup didn't recognized v0.10.14
